config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :notifications
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :rentals
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get '/search/books' , to: "search#books"
  get '/search/index' , to: "search#index"
  get '/search/allbooks' , to: "search#allbooks"
  get '/contact', to: "welcome#contact"
  get '/about', to: "welcome#about"
  get '/hours', to: "welcome#hours"
  get '/events', to: "welcome#events"

  get '/order_items/order_all', to: 'order_items#order_all'

  post '/rentals/:id', to: "rentals#update"
  post '/rentals/renew/:id', to: "rentals#renew"

  post '/order_items/order_all', to: "order_items#order_all"

  resources :categories
  resources :books
  resources :order_items, :except => [:show]
  resources :carts, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/admin', to: "rails_admin/main#dashboard"
  get "/book_report", to: "welcome#report"
  root to: "welcome#index"

end

app/models/rental.rb
class Rental < ApplicationRecord
    belongs_to :user, :foreign_key => :userId
    belongs_to :book, :foreign_key => :isbn
    has_many :order_items
    has_many :notifications


end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /rentals
  # GET /rentals.json

  def index
    @current_rentals = Rental.where("userId = ? and isReturned = 0", current_user.id)
    @past_rentals = Rental.where("userId = ? and isReturned = 1", current_user.id).paginate(:page => params[:page], :per_page => 5)
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    @rental = Rental.new
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals
  # POST /rentals.json
  def create
    #@rental = Rental.new(rental_params)
    @rental = Rental.new
    @rental.dateRented = Date.current
    @rental.dateDue = Date.current.next_month
    @rental.daysLeft = (Date.current.next_month - Date.current).to_i
    @rental.isRenewed = 0
    @rental.isReturned = 0
    @rental.fee = 0.00
    @rental.userId = current_user.id
    @rental.isbn = params["isbn"]

    respond_to do |format|
      if @rental.save
        @book = Book.find_by isbn: params["isbn"]
        @book.copiesLeft = params["copies"].to_i - 1
        @book.save

        format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    @rental = Rental.find(params["id"])
    @rental.isReturned = 1
    @rental.dateReturned = Date.current

    respond_to do |format|
      if @rental.save
        @book = Book.find_by isbn: params["isbn"]
        @book.copiesLeft = params["copies"].to_i + 1
        @book.save

        format.html { redirect_to @rental, notice: 'Rental was successfully returned.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/renew/1
  # PATCH/PUT /rentals/renew/1.json
  def renew
    @rental = Rental.find(params["id"])
    @rental.dateDue = params["date"].to_date + 2.weeks
    @rental.daysLeft = ((params["date"].to_date + 2.weeks) - Date.current).to_i
    @rental.isRenewed = 1

    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: 'Rental was successfully renewed.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params["id"])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_params
      params.require(:rental).permit(:dateRented, :dateDue, :daysLeft, :isRenewed, :isReturned, :dateReturned, :fee)
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_form.html.erb
<%= form_with(model: rental, local: true) do |form| %>
  <% if rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dateRented %>
    <%= form.date_select :dateRented, id: :rental_dateRented %>
  </div>

  <div class="field">
    <%= form.label :dateDue %>
    <%= form.date_select :dateDue, id: :rental_dateDue %>
  </div>

  <div class="field">
    <%= form.label :daysLeft %>
    <%= form.number_field :daysLeft, id: :rental_daysLeft %>
  </div>

  <div class="field">
    <%= form.label :returned %>
    <%= form.check_box :returned, id: :rental_returned %>
  </div>

  <div class="field">
    <%= form.label :dateReturned %>
    <%= form.date_select :dateReturned, id: :rental_dateReturned %>
  </div>

  <div class="field">
    <%= form.label :fee %>
    <%= form.text_field :fee, id: :rental_fee %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<p id="notice"><%= notice %></p>

<% if (@current_rentals.blank?) && (@past_rentals.blank?) -%>
  <h1>Rentals</h1>
  <div class="jumbotron">
    <p style="line-height: 30px;">
      You don't have any rentals. Search for books by title, author, or category and rent the ones you like.
    </p>
  </div>
<% else -%>
  <div class="well">
    <h1>Current Rentals</h1>
    <table class="table">
      <thead>
        <tr>
          <th>ISBN</th>
          <th>Title</th>
          <th>Date Rented</th>
          <th>Date Due</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @current_rentals.each do |rental| %>
          <tr>
            <td><%= rental.isbn %></td>
            <td><%= rental.book.title %></td>
            <td><%= rental.dateRented.strftime("%B %-d, %Y") %></td>
            <%# Text turns red if rental is overdue %>
            <% if Date.current > rental.dateDue -%>
              <td class="text-danger">
            <% else -%>
              <td>
            <% end -%>
            <%= rental.dateDue.strftime("%B %-d, %Y") %></td>
            <td>
              <form name="return" action="/rentals/<%= rental.id %>" method="post">
                <input type="hidden" name="id" value="<%= rental.id %>">
                <input type="hidden" name="isbn" value="<%= rental.isbn %>">
                <input type="hidden" name="copies" value="<%= rental.book.copiesLeft %>">
                <input type="submit" value="Return">
              </form>
            </td>
            <td>
              <%# Renew button only appears if rental has not been renewed before
              (to prevent spam of renewal) and has no fees (cannot renew if overdue) %>
              <% if (!rental.isRenewed) && (rental.fee == 0) -%>
                <form name="renew" action="/rentals/renew/<%= rental.id %>" method="post">
                  <input type="hidden" name="id" value="<%= rental.id %>">
                  <input type="hidden" name="date" value="<%= rental.dateDue %>">
                  <input type="submit" value="Renew">
                </form>
              <% end -%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="well">
    <h1>Past Rentals</h1>
    <table class="table">
      <thead>
        <tr>
          <th>ISBN</th>
          <th>Title</th>
          <th>Date Rented</th>
          <th>Date Due</th>
          <th>Date Returned</th>
        </tr>
      </thead>

      <tbody>
        <% @past_rentals.each do |rental| %>
          <tr>
            <td><%= rental.isbn %></td>
            <td><%= rental.book.title %></td>
            <td><%= rental.dateRented.strftime("%B %-d, %Y") %></td>
            <td><%= rental.dateDue.strftime("%B %-d, %Y") %></td>
            <td><%= rental.dateReturned.strftime("%B %-d, %Y") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="text-center">
      <%= will_paginate @past_rentals %></div>
  </div>

<% end -%>

app/views/rentals/new.html.erb
<h1>New Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<h1>Rental Information</h1>

<p>
  <strong>ISBN:</strong>
  <%= @rental.isbn %>
</p>

<p>
  <strong>Title:</strong>
  <%= @rental.book.title %>
</p>

<p>
  <strong>Date Rented:</strong>
  <%= @rental.dateRented.strftime("%B %-d, %Y") %>
</p>

<p>
  <strong>Date Due:</strong>
  <%= @rental.dateDue.strftime("%B %-d, %Y") %>
</p>

<% if @rental.dateReturned != nil -%>
  <p>
    <strong>Date Returned:</strong>
    <%= @rental.dateReturned.strftime("%B %-d, %Y") %>
  </p>
<% end -%>

<!--<%= link_to 'Edit', edit_rental_path(@rental) %> |-->
<%= link_to 'Back', rentals_path, :class => "btn btn-default" %>