config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :notifications
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :rentals
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get '/search/books' , to: "search#books"
  get '/search/index' , to: "search#index"
  get '/search/allbooks' , to: "search#allbooks"
  get '/contact', to: "welcome#contact"
  get '/about', to: "welcome#about"
  get '/hours', to: "welcome#hours"
  get '/events', to: "welcome#events"

  get '/order_items/order_all', to: 'order_items#order_all'

  post '/rentals/:id', to: "rentals#update"
  post '/rentals/renew/:id', to: "rentals#renew"

  post '/order_items/order_all', to: "order_items#order_all"

  resources :categories
  resources :books
  resources :order_items, :except => [:show]
  resources :carts, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/admin', to: "rails_admin/main#dashboard"
  get "/book_report", to: "welcome#report"
  root to: "welcome#index"

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  validates :name, presence:true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category_id = params[:id]
    @categoryName = Category.find(@category_id).name

    @books = Book.where("category_id = ?", @category_id)

  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to "/categories", notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
  <%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(category.errors.count, "error") %>
      prohibited this category from being saved:</h2>

    <ul>
      <% category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, required:true %>
    <%= form.text_field :name, id: :category_name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-lg btn-success" %>
  </div>
  <% end %>

app/views/categories/edit.html.erb
<div class="col-md-6 col-md-offset-3">

<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category, class: "btn btn-sm" %> |
<%= link_to 'Back', categories_path, class: "btn btn-sm" %>
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"> Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td><%= link_to 'Show books in category', category_path(category.id) %></td>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>New Category</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Back', categories_path, class: "btn btn-primary"%>
  </div>

app/views/categories/show.html.erb
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-md-8 col-md-offset-3" style="border: 2px dashed rgba(27,31,35,0.3); border-radius: 5px; padding: 30px; width: 648.33px;">
        <h1>Books in category: <%= @categoryName %></h1>

    <% if @books.length <= 0 %>
    <p>No books in category...</p>
  <% else %>
    <% @books.each do |book| %>
    <a href="/books/<%=book.isbn%>">
      <%= book.title%>
    </a>
    <hr/>
    <% end %>
    <% end %>
  </div>
</div>

<%= link_to 'Back', categories_path, class: "btn btn-sm" %>